# install-task.ps1 -- register PM Panel as a Windows Scheduled Task that
# starts at boot and stays up after RDP disconnect / logoff.
#
# Run as Administrator:
#   powershell -ExecutionPolicy Bypass -File .\install-task.ps1
#
# To uninstall:
#   Unregister-ScheduledTask -TaskName "PM Panel" -Confirm:$false

#requires -RunAsAdministrator

$ErrorActionPreference = 'Stop'
$ServerDir  = "C:\Users\Administrator\Documents\pm-panel\server"
$NodeExe    = "C:\Program Files\nodejs\node.exe"
$TaskName   = "PM Panel"
$WrapperPs1 = Join-Path $ServerDir "run-service.ps1"
$LogPath    = Join-Path $ServerDir "pm-panel.log"
$Port       = 4000

if (-not (Test-Path $NodeExe))   { throw "node.exe not found at $NodeExe" }
if (-not (Test-Path $ServerDir)) { throw "Server dir not found at $ServerDir" }

Write-Host "[1/5] Stopping any running pm-panel instance..." -ForegroundColor Cyan
try { & (Join-Path $ServerDir "pm-panel.bat") stop 2>$null } catch {}
Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue | ForEach-Object {
  try { Stop-Process -Id $_.OwningProcess -Force -ErrorAction SilentlyContinue } catch {}
}
Start-Sleep -Seconds 1

Write-Host "[2/5] Writing service wrapper -> $WrapperPs1" -ForegroundColor Cyan
$wrapper = @'
# Auto-generated by install-task.ps1 -- do not edit by hand.
$ErrorActionPreference = 'Stop'
$ServerDir = "C:\Users\Administrator\Documents\pm-panel\server"
$NodeExe   = "C:\Program Files\nodejs\node.exe"
$LogPath   = Join-Path $ServerDir "pm-panel.log"
Set-Location $ServerDir

# Rotate log if it grows past 5 MB so the disk doesn't fill over months.
if (Test-Path $LogPath) {
  $f = Get-Item $LogPath
  if ($f.Length -gt 5MB) {
    $bak = Join-Path $ServerDir ("pm-panel." + (Get-Date -Format yyyyMMdd-HHmmss) + ".log")
    Move-Item $LogPath $bak -Force
  }
}

# Tee stdout+stderr to the log AND to console.
& $NodeExe index.js *>&1 | ForEach-Object { $_ | Out-String } |
  Out-File -FilePath $LogPath -Append -Encoding utf8
'@
Set-Content -Path $WrapperPs1 -Value $wrapper -Encoding UTF8

Write-Host "[3/5] Unregistering any previous '$TaskName' task..." -ForegroundColor Cyan
Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue | Out-Null

Write-Host "[4/5] Registering scheduled task '$TaskName'..." -ForegroundColor Cyan
$action    = New-ScheduledTaskAction -Execute "powershell.exe" `
              -Argument "-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$WrapperPs1`"" `
              -WorkingDirectory $ServerDir
$trigger   = New-ScheduledTaskTrigger -AtStartup
$principal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -LogonType ServiceAccount -RunLevel Highest
$settings  = New-ScheduledTaskSettingsSet `
              -AllowStartIfOnBatteries `
              -DontStopIfGoingOnBatteries `
              -StartWhenAvailable `
              -RestartCount 99 -RestartInterval (New-TimeSpan -Minutes 1) `
              -ExecutionTimeLimit (New-TimeSpan -Seconds 0) `
              -MultipleInstances IgnoreNew

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
  -Principal $principal -Settings $settings `
  -Description "PM Panel API -- auto-start at boot, restart on failure." | Out-Null

Write-Host "[5/5] Starting task and verifying port $Port..." -ForegroundColor Cyan
Start-ScheduledTask -TaskName $TaskName
$ok = $false
for ($i = 0; $i -lt 20; $i++) {
  Start-Sleep -Milliseconds 500
  if (Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue) { $ok = $true; break }
}
if ($ok) {
  Write-Host ""
  Write-Host "[OK] PM Panel is running as scheduled task '$TaskName' on http://localhost:$Port" -ForegroundColor Green
  Write-Host "  - Survives logoff and reboot."
  Write-Host "  - Auto-restarts on crash (1 min cooldown, 99 retries)."
  Write-Host "  - Log: $LogPath  (rotated at 5 MB)"
  Write-Host "  - Manage:"
  Write-Host "      Stop-ScheduledTask  -TaskName '$TaskName'"
  Write-Host "      Start-ScheduledTask -TaskName '$TaskName'"
  Write-Host "      Unregister-ScheduledTask -TaskName '$TaskName' -Confirm:`$false"
} else {
  Write-Host ""
  Write-Host "[WARN] Task started but nothing is listening on port $Port yet." -ForegroundColor Yellow
  Write-Host "  Tail the log to investigate:  Get-Content '$LogPath' -Tail 50 -Wait"
}
